from odoo import models


class ShippingInstructionXlsx(models.AbstractModel):
    _name = 'report.sci_goexcel_freight.report_si_xlsx'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, lines):
        format1 = workbook.add_format({'font_size': 14, 'align': 'vcenter', 'bold': True})
        format2 = workbook.add_format({'font_size': 14, 'align': 'vcenter'})
        merge_format = workbook.add_format({'align': 'center', 'valign': 'vcenter', 'fg_color': 'yellow'})
        sheet = workbook.add_worksheet('SI Report')
        if lines.direction == 'export' or lines.service_type == 'land':
            sheet.merge_range(0, 1, 0, 3, 'Merged Cells', merge_format)
            sheet.merge_range(2, 1, 2, 3, 'Merged Cells', merge_format)
            sheet.merge_range(3, 1, 3, 3, 'Merged Cells', merge_format)
            sheet.merge_range(4, 1, 4, 3, 'Merged Cells', merge_format)
            sheet.merge_range(7, 1, 7, 3, 'Merged Cells', merge_format)
            sheet.set_column(0, 0, 35)
            sheet.set_column(0, 1, 40)
            sheet.set_column(0, 2, 35)
            sheet.set_column(0, 3, 40)
            sheet.write(0, 0, 'Booking No.', format1)
            sheet.write(0, 1, lines.booking_ref.booking_no, format2)
            sheet.write(1, 0, 'Freight Type', format1)
            sheet.write(1, 1, lines.freight_type, format2)
            sheet.write(1, 2, 'Bill Of Lading Type', format1)
            sheet.write(1, 3, lines.bill_of_lading_type, format2)
            sheet.write(2, 0, 'Shipper', format1)
            sheet.write(2, 1, lines.shipper, format2)
            sheet.write(3, 0, 'Consignee', format1)
            sheet.write(3, 1, lines.consignee, format2)
            sheet.write(4, 0, 'Notify Party', format1)
            sheet.write(4, 1, lines.notify_party, format2)
            sheet.write(5, 0, 'Vessel, Voyage & Direction', format1)
            sheet.write(5, 1, lines.vessel + '/' + lines.voyage_no + '/' + lines.direction, format2)
            sheet.write(5, 2, 'Port of Load', format1)
            sheet.write(5, 3, lines.port_of_loading_input, format2)
            sheet.write(6, 0, 'Port of Discharge', format1)
            sheet.write(6, 1, lines.port_of_discharge_input, format2)
            sheet.write(6, 2, 'Final Destination', format1)
            sheet.write(6, 3, lines.place_of_delivery, format2)
            sheet.write(7, 0, 'Remark', format1)
            sheet.write(7, 1, lines.note, format2)
        if lines.service_type == 'ocean' or lines.service_type == 'air':
            if lines.direction == 'import':
                sheet.set_column(5, 0, 20)
                sheet.set_column(5, 1, 160)
                sheet.merge_range(0, 0, 0, 1, 'Merged Cells', merge_format)
                sheet.merge_range(1, 0, 1, 1, 'Merged Cells', merge_format)
                sheet.merge_range(2, 0, 2, 1, 'Merged Cells', merge_format)
                sheet.merge_range(3, 0, 3, 1, 'Merged Cells', merge_format)
                sheet.merge_range(6, 0, 6, 1, 'Merged Cells', merge_format)
                sheet.merge_range(7, 0, 7, 1, 'Merged Cells', merge_format)
                sheet.merge_range(8, 0, 8, 1, 'Merged Cells', merge_format)
                sheet.merge_range(9, 0, 9, 1, 'Merged Cells', merge_format)
                sheet.merge_range(10, 0, 10, 1, 'Merged Cells', merge_format)
                sheet.merge_range(11, 0, 11, 1, 'Merged Cells', merge_format)
                sheet.merge_range(12, 0, 12, 1, 'Merged Cells', merge_format)
                sheet.merge_range(13, 0, 13, 1, 'Merged Cells', merge_format)
                sheet.merge_range(14, 0, 14, 1, 'Merged Cells', merge_format)
                sheet.write(0, 0, 'TO WHOM IT MAY CONCERN:', format1)
                sheet.write(1, 0, 'SUBJECT: SHIPPING INSTRUCTION FOR CONSIGNMENT', format1)
                sheet.write(2, 0, 'REFER TO ABOVE CAPTIONED, PLEASE KINDLY FOLLOW BELOW CONSIGNMENT SHIPPING INSTRUCTION FOR ALL SHIPMENT TO MALAYSIA:', format2)
                if lines.direction == 'import' and lines.service_type == 'air':
                    sheet.write(3, 0, 'MAWB', format1)
                    sheet.write(4, 0, 'SHIPPER :', format1)
                    sheet.write(4, 1, lines.shipper, format2)
                    sheet.write(5, 0, 'CONSIGNEE :', format1)
                    sheet.write(5, 1, lines.consignee, format2)
                    sheet.write(6, 0, 'HAWB', format1)
                    sheet.write(7, 0, 'ACTUAL SHIPPER', format2)
                    sheet.write(8, 0, 'ACTUAL CONSIGNEE', format2)
                if lines.direction == 'import' and lines.service_type == 'ocean':
                    sheet.write(3, 0, 'MBL /OBL', format1)
                    sheet.write(4, 0, 'SHIPPER :', format1)
                    sheet.write(4, 1, lines.shipper, format2)
                    sheet.write(5, 0, 'CONSIGNEE :', format1)
                    sheet.write(5, 1, lines.consignee, format2)
                    sheet.write(6, 0, 'HBL :', format1)
                    sheet.write(7, 0, 'ACTUAL SHIPPER', format1)
                    sheet.write(8, 0, 'ACTUAL CONSIGNEE', format1)
                sheet.write(9, 0, 'NOTE :', format1)
                sheet.write(10, 0, 'ALL DOCUMENT MUST BE CHECK AND CONFIRMED BY US BEFORE FINAL B/L OR AIRWAYBILL IS ISSUED.', format2)
                sheet.write(11, 0, 'WE NEED TO RECEIVE THE FULL PRE-ALERT 2DAYS (48 HOURS- SEAFREIGHT) AND 1 DAY (24 HOURS- AIRFREIGHT) FOR MANIFEST PURPOSE.', format1)
                sheet.write(12, 0, 'ANY FAILURE IN COMPLYING TO THE LEAD TIMES FOR ADVANCE MANIFEST WILL INCUR CUSTOMS PENALTIES WHICH WE SHALL HOLD YOUR SIDE ACCOUNTABLE.', format2)
                sheet.write(13, 0, 'THANKS AND BEST REGARDS', format1)
                print(self)
                sheet.write(14, 0, 'THE MANAGEMENT OF ' + lines.company_id.name , format1)

