{
    "name": "GoExcel Freight",
    "version": "12.0.1.0.0",
    "category": "Transport",
    "license": 'LGPL-3',
    "summary": """Freight Management for Freight Forwarding.""",
    'description': 'Freight Management for Freight Forwarder (Air, Land and Ocean)',
    "author": "Excelroot Technology Sdn Bhd",
    "depends": ['product', 'account', 'sale', 'mail','website', 'base'],
    'sequence': 1,
    'application': True,
    "data": [
        'security/freight_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'report/booking_confirmation.xml',
        'report/bill_of_lading.xml',
        'report/delivery_order.xml',
        'report/bl_report.xml',
        'report/si_report.xml',
        #'report/job_sheet.xml',
        'views/booking_view.xml',
        'data/booking_confirmation_mail_template.xml',
        'data/bl_mail_template.xml',
        'data/bol_mail_template.xml',
        'data/do_mail_template.xml',
        'data/si_mail_template.xml',
        'views/subjob_view.xml',
        'views/js_templates.xml',
        'views/configure_view.xml',
        #'views/shipping_instruction_confirmation_view.xml',
        'views/shipping_instruction_view.xml',
        'views/bol_view.xml',
        'views/shipping_instruction_templates.xml',
        'views/sales_quotation_view.xml',
        'views/cron.xml',
        #'views/cost_profit.xml',
        'views/res_partner_view.xml',
        #'views/invoice_view.xml',
        'views/booking_report.xml',
        'views/invoice_wizard.xml',
        'views/booking_line_view.xml',
        'views/bol_line_view.xml',
        'views/si_line_view.xml',
    ],
}