from . import configure
from . import transport_rft
from . import res_partner
from . import dispatch_trip
from . import fleet
from . import sale_quotation
from . import invoice
from . import res_config_settings
from . import freight_booking