# -*- coding: utf-8 -*-
{
    "name": "GoExcel Logistics Warehouse",
    "version": "12.0.1.0.0",
    "category": "Transport",
    "license": 'LGPL-3',
    "summary": """Warehouse """,
    'description': 'Warehouse for Logistics',
    "author": "Excelroot Technology Sdn Bhd",
    "depends": ['base','purchase','sale_management','account','stock','mail','sale_revision_history','google_drive_attachment'],
    'sequence': 2,
    'application': True,
    "data": [
        'security/warehouse_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/res_config_settings_view.xml',
        'views/user_warehouse_view.xml',
        'views/tallysheet_view.xml',
        'views/stock_picking_view.xml',
        'views/google_drive_attachment_view.xml',
        #'views/loading_plan_view.xml',
        'views/sales_quotation_view.xml',
        'views/configure_view.xml',
        'views/gate_pass_view.xml',
        'views/sale_letter_pad.xml',
        'wizards/container_survey_view.xml',
        'wizards/gate_pass_view.xml',
        'wizards/loading_plan_wizard_view.xml',
        'reports/job_sheet.xml',
        'reports/report_tally_sheet.xml',
        #'reports/report_account_invoice.xml',
        'reports/report_delivery_order.xml',
        #'reports/report_sq_warehouse_inherit.xml',
        'views/invoice_wizard.xml',
        'reports/gate_pass.xml',
        'reports/idd.xml',
    ],
}
